profiles:
  default:
    # Voting duration of 5 days
    duration: 5d
    # Pass threshold of 50% (i.e. majority)
    pass_threshold: 50
    allowed_voters:
      teams: [ccc-steerco]
      users: []

    # Periodic status check - automatically check the vote after 1 day
    periodic_status_check: 1d

    # Close vote on passing
    close_on_passing: true