#!/usr/bin/env bash
# Creates behavioural-test Entra ID apps/SPs for Azure fixtures and writes gitignored azure-env.sh.
# Run from anywhere:
#   ./modules/cloud-api-test/user-creation/provision-azure-test-users.sh
# Then:
#   source modules/cloud-api-test/user-creation/azure-env.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_FILE="$SCRIPT_DIR/azure-env.sh"

if ! command -v az >/dev/null 2>&1; then
  echo "error: Azure CLI (az) is required" >&2
  exit 1
fi

if ! az account show >/dev/null 2>&1; then
  echo "error: run 'az login' first" >&2
  exit 1
fi

TENANT_ID="${AZURE_TENANT_ID:-$(az account show --query tenantId -o tsv)}"
SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"
LOG_ANALYTICS_WORKSPACE_ID="${AZURE_LOG_ANALYTICS_WORKSPACE_ID:-}"
VM_HOSTNAME="${AZURE_VM_HOSTNAME:-}"

# Defaults match cfi-testing/privateer-config/finos-integration/cloud-storage/azure-cloud-storage.yml
RESOURCE_GROUP="${AZURE_STORAGE_RESOURCE_GROUP:-finos-ccc-integration-storage-rg}"
STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:-finoscccintegrationmain}"

STORAGE_SCOPE="$(az storage account show \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --query id -o tsv 2>/dev/null || true)"

if [ -z "$STORAGE_SCOPE" ] || [ "$STORAGE_SCOPE" = "null" ]; then
  echo "error: storage account $STORAGE_ACCOUNT not found in $RESOURCE_GROUP" >&2
  echo "set AZURE_STORAGE_RESOURCE_GROUP / AZURE_STORAGE_ACCOUNT and retry" >&2
  exit 1
fi

INSTANCE_ID="${INSTANCE_ID:-$(date -u +"%Y%m%dt%H%M%Sz")}"

# runner_key|display_name_suffix|role_name|env_prefix
USERS=(
  "testUserNoAccess|test-user-no-access||AZURE_TEST_USER_NO_ACCESS"
  "testUserRead|test-user-read|Storage Blob Data Reader|AZURE_TEST_USER_READ"
  "testUserWrite|test-user-write|Storage Blob Data Contributor|AZURE_TEST_USER_WRITE"
  "testUserAdmin|test-user-admin-access|Storage Blob Data Owner|AZURE_TEST_USER_ADMIN"
)

ensure_app_and_sp() {
  local display_name="$1"
  local app_id sp_id client_secret

  app_id="$(az ad app list --display-name "$display_name" --query "[0].appId" -o tsv 2>/dev/null || true)"
  if [ -z "$app_id" ] || [ "$app_id" = "null" ]; then
    echo "Creating app: $display_name"
    app_id="$(az ad app create --display-name "$display_name" --query appId -o tsv)"
  else
    echo "Reusing app: $display_name ($app_id)"
  fi

  sp_id="$(az ad sp list --display-name "$display_name" --query "[0].id" -o tsv 2>/dev/null || true)"
  if [ -z "$sp_id" ] || [ "$sp_id" = "null" ]; then
    sp_id="$(az ad sp create --id "$app_id" --query id -o tsv)"
  fi

  # New secret each run (secrets are write-only).
  client_secret="$(az ad app credential reset --id "$app_id" --query password -o tsv)"
  if [ -z "$client_secret" ] || [ "$client_secret" = "null" ]; then
    echo "error: failed to create client secret for $display_name" >&2
    exit 1
  fi

  APP_ID_RESULT="$app_id"
  SP_ID_RESULT="$sp_id"
  SECRET_RESULT="$client_secret"
}

assign_role_if_needed() {
  local sp_id="$1"
  local role_name="$2"
  [ -z "$role_name" ] && return 0

  if az role assignment list \
    --assignee "$sp_id" \
    --scope "$STORAGE_SCOPE" \
    --role "$role_name" \
    --query "[0].id" -o tsv 2>/dev/null | grep -q .; then
    echo "Role already assigned: $role_name"
    return 0
  fi

  echo "Assigning role: $role_name"
  az role assignment create \
    --assignee "$sp_id" \
    --role "$role_name" \
    --scope "$STORAGE_SCOPE" \
    --output none
}

{
  echo "# Generated by provision-azure-test-users.sh — do not commit."
  echo "# Source before integration / behavioural runs:"
  echo "#   source modules/cloud-api-test/user-creation/azure-env.sh"
  echo ""
  printf 'export AZURE_TENANT_ID=%q\n' "$TENANT_ID"
  printf 'export AZURE_SUBSCRIPTION_ID=%q\n' "$SUBSCRIPTION_ID"
  if [ -n "$LOG_ANALYTICS_WORKSPACE_ID" ]; then
    printf 'export AZURE_LOG_ANALYTICS_WORKSPACE_ID=%q\n' "$LOG_ANALYTICS_WORKSPACE_ID"
  fi
  if [ -n "$VM_HOSTNAME" ]; then
    printf 'export AZURE_VM_HOSTNAME=%q\n' "$VM_HOSTNAME"
  fi
  echo ""
} >"$OUT_FILE"

for spec in "${USERS[@]}"; do
  IFS='|' read -r _runner_key suffix role_name env_prefix <<<"$spec"
  display_name="cfi-${INSTANCE_ID}-${suffix}"

  echo "--- $display_name ---"
  ensure_app_and_sp "$display_name"
  assign_role_if_needed "$SP_ID_RESULT" "$role_name"

  {
    printf 'export %s_CLIENT_ID=%q\n' "$env_prefix" "$APP_ID_RESULT"
    printf 'export %s_CLIENT_SECRET=%q\n' "$env_prefix" "$SECRET_RESULT"
    printf 'export %s_OBJECT_ID=%q\n' "$env_prefix" "$SP_ID_RESULT"
    printf 'export %s_USER_NAME=%q\n' "$env_prefix" "$display_name"
    echo ""
  } >>"$OUT_FILE"
done

chmod 600 "$OUT_FILE"
echo "Wrote $OUT_FILE"
