#!/usr/bin/env bash
# Idempotent: reuses Entra apps/SPs; refreshes azure-env.sh from terraform outputs when set.
# Run: ./modules/cloud-api-test/environment-config/provision-azure.sh
# Use ROTATE_SECRETS=1 to force new client secrets.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

OUT_FILE="${OUT_FILE:-$SCRIPT_DIR/azure-env.sh}"
TFSTATE="$SCRIPT_DIR/../terraform/azure/terraform.tfstate"
STALE_VERSION_ID="${STALE_VERSION_ID:-00000000000000000000000000000000}"

if ! command -v az >/dev/null 2>&1; then
  echo "error: Azure CLI (az) is required" >&2
  exit 1
fi

if ! az account show >/dev/null 2>&1; then
  echo "error: run 'az login' first" >&2
  exit 1
fi

TENANT_ID="${AZURE_TENANT_ID:-$(az account show --query tenantId -o tsv)}"
SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"
LOG_ANALYTICS_WORKSPACE_ID="${AZURE_LOG_ANALYTICS_WORKSPACE_ID:-}"
VM_HOSTNAME="${AZURE_VM_HOSTNAME:-}"

if [[ -f "$TFSTATE" ]] && command -v jq >/dev/null 2>&1; then
  if [[ -z "$LOG_ANALYTICS_WORKSPACE_ID" ]]; then
    LOG_ANALYTICS_WORKSPACE_ID="$(jq -r '.outputs.logging.value.azure_log_analytics_workspace_id // empty' "$TFSTATE" | tr -d '\n')"
  fi
  if [[ -z "$VM_HOSTNAME" ]]; then
    VM_HOSTNAME="$(jq -r '.outputs.virtual_machines.value.host_name // empty' "$TFSTATE" | tr -d '\n')"
  fi
fi

RESOURCE_GROUP="${AZURE_STORAGE_RESOURCE_GROUP:-finos-ccc-integration-rg}"
STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:-finoscccintegrationmain}"

STORAGE_SCOPE="$(az storage account show \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --query id -o tsv 2>/dev/null || true)"

if [[ -z "$STORAGE_SCOPE" || "$STORAGE_SCOPE" == "null" ]]; then
  echo "error: storage account $STORAGE_ACCOUNT not found in $RESOURCE_GROUP" >&2
  exit 1
fi

INSTANCE_ID="${INSTANCE_ID:-}"
if [[ -z "$INSTANCE_ID" ]]; then
  existing_name="$(read_env_export "$OUT_FILE" "AZURE_TEST_USER_NO_ACCESS_USER_NAME" || true)"
  if [[ -n "$existing_name" && "$existing_name" =~ ^cfi-(.+)-test-user-no-access$ ]]; then
    INSTANCE_ID="${BASH_REMATCH[1]}"
    echo "==> Reusing instance id from $OUT_FILE: $INSTANCE_ID"
  fi
fi
INSTANCE_ID="${INSTANCE_ID:-integration}"

USERS=(
  "test-user-no-access|test-user-no-access||AZURE_TEST_USER_NO_ACCESS"
  "test-user-read|test-user-read|Storage Blob Data Reader|AZURE_TEST_USER_READ"
  "test-user-write|test-user-write|Storage Blob Data Contributor|AZURE_TEST_USER_WRITE"
  "test-user-admin|test-user-admin-access|Storage Blob Data Owner|AZURE_TEST_USER_ADMIN"
)

ensure_app_and_sp() {
  local display_name="$1" env_prefix="$2"
  local app_id sp_id client_secret existing_secret

  app_id="$(az ad app list --display-name "$display_name" --query "[0].appId" -o tsv 2>/dev/null || true)"
  if [[ -z "$app_id" || "$app_id" == "null" ]]; then
    echo "Creating app: $display_name"
    app_id="$(az ad app create --display-name "$display_name" --query appId -o tsv)"
  else
    echo "Reusing app: $display_name ($app_id)"
  fi

  sp_id="$(az ad sp list --display-name "$display_name" --query "[0].id" -o tsv 2>/dev/null || true)"
  if [[ -z "$sp_id" || "$sp_id" == "null" ]]; then
    echo "Creating service principal: $display_name"
    sp_id="$(az ad sp create --id "$app_id" --query id -o tsv)"
  else
    echo "Reusing service principal: $display_name"
  fi

  client_secret=""
  if [[ "${ROTATE_SECRETS:-0}" != "1" && -f "$OUT_FILE" ]]; then
    client_secret="$(read_env_export "$OUT_FILE" "${env_prefix}_CLIENT_SECRET" || true)"
  fi
  if [[ -z "$client_secret" ]]; then
    echo "Creating client secret for $display_name"
    client_secret="$(az ad app credential reset --id "$app_id" --query password -o tsv)"
  else
    echo "Reusing client secret from $OUT_FILE for $display_name"
  fi

  if [[ -z "$client_secret" || "$client_secret" == "null" ]]; then
    echo "error: failed to obtain client secret for $display_name" >&2
    exit 1
  fi

  APP_ID_RESULT="$app_id"
  SP_ID_RESULT="$sp_id"
  SECRET_RESULT="$client_secret"
}

assign_role_if_needed() {
  local sp_id="$1" role_name="$2"
  [[ -z "$role_name" ]] && return 0

  if az role assignment list \
    --assignee "$sp_id" \
    --scope "$STORAGE_SCOPE" \
    --role "$role_name" \
    --query "[0].id" -o tsv 2>/dev/null | grep -q .; then
    echo "Role already assigned: $role_name"
    return 0
  fi

  echo "Assigning role: $role_name"
  az role assignment create \
    --assignee "$sp_id" \
    --role "$role_name" \
    --scope "$STORAGE_SCOPE" \
    --output none
}

{
  echo "# Generated by provision-azure.sh — do not commit."
  echo "# Source: source modules/cloud-api-test/environment-config/azure-env.sh"
  echo "# Re-run after terraform apply to refresh fixture vars (identities reused unless ROTATE_SECRETS=1)."
  echo ""
  printf 'export AZURE_TENANT_ID=%q\n' "$TENANT_ID"
  printf 'export AZURE_SUBSCRIPTION_ID=%q\n' "$SUBSCRIPTION_ID"
  [[ -n "$LOG_ANALYTICS_WORKSPACE_ID" ]] && printf 'export AZURE_LOG_ANALYTICS_WORKSPACE_ID=%q\n' "$LOG_ANALYTICS_WORKSPACE_ID"
  [[ -n "$VM_HOSTNAME" ]] && printf 'export AZURE_VM_HOSTNAME=%q\n' "$VM_HOSTNAME"
  printf 'export STALE_VERSION_ID=%q\n' "$STALE_VERSION_ID"
  echo ""
} >"$OUT_FILE"

for spec in "${USERS[@]}"; do
  IFS='|' read -r _identity_key suffix role_name env_prefix <<<"$spec"
  display_name="cfi-${INSTANCE_ID}-${suffix}"

  echo "--- $display_name ---"
  ensure_app_and_sp "$display_name" "$env_prefix"
  assign_role_if_needed "$SP_ID_RESULT" "$role_name"

  {
    printf 'export %s_CLIENT_ID=%q\n' "$env_prefix" "$APP_ID_RESULT"
    printf 'export %s_CLIENT_SECRET=%q\n' "$env_prefix" "$SECRET_RESULT"
    printf 'export %s_OBJECT_ID=%q\n' "$env_prefix" "$SP_ID_RESULT"
    printf 'export %s_USER_NAME=%q\n' "$env_prefix" "$display_name"
    echo ""
  } >>"$OUT_FILE"
done

chmod 600 "$OUT_FILE"
echo "Wrote $OUT_FILE"
