package reporters

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"github.com/cucumber/godog/formatters"
	messages "github.com/cucumber/messages/go/v21"
)

// SummaryResult represents a single scenario result for the summary report
type SummaryResult struct {
	Control      string
	Scenario     string
	ScenarioName string // Scenario with exclusion tag suffix (e.g. "Name - NotTestable")
	Badge        string // .e.g., "Not Testable"
	IsPolicy     bool
	Outcome      string // "PASSING", "FAILING" - same logic as OCSF
	exclusionTag string // NotTested, NotTestable, Duplicate
	failed       bool
}

// summaryCollector holds all results for the summary report
var summaryCollector struct {
	mu      sync.Mutex
	results []SummaryResult
	current *SummaryResult
}

// Control tag pattern: CCC.XXX.YYYY or CCC.XXX.YYYY.ARZZ
var controlPattern = "CCC."

// SummaryFormatter is a godog formatter that collects results for a summary report
type SummaryFormatter struct {
	out            io.Writer
	currentFeature string
	currentResult  *SummaryResult
}

// Feature captures feature information (control ID and description, as in html-formatter)
func (f *SummaryFormatter) Feature(gd *messages.GherkinDocument, uri string, c []byte) {
	if gd.Feature != nil {
		// Use full feature name (e.g. "CCC.Core.CN02.AR01 - Data Encryption at Rest")
		// matching html-formatter display
		f.currentFeature = strings.TrimSpace(gd.Feature.Name)
	}
}

// Pickle captures scenario information
func (f *SummaryFormatter) Pickle(pickle *messages.Pickle) {
	// Finalize previous scenario if any
	if f.currentResult != nil {
		f.finalizeResult()
	}

	// Determine Policy vs Behavioural from tags
	isPolicy := false
	exclusionTag := ""
	for _, tag := range pickle.Tags {
		if tag.Name == "@Policy" {
			isPolicy = true
		} else if tag.Name == "@NotTested" {
			exclusionTag = "NotTested"
		} else if tag.Name == "@NotTestable" {
			exclusionTag = "NotTestable"
		} else if tag.Name == "@Duplicate" {
			exclusionTag = "Duplicate"
		}
	}

	scenarioName := pickle.Name

	control := f.currentFeature
	if control == "" {
		// Fallback: extract from tags (e.g. @CCC.Core.CN05.AR03 or @CCC.Core.CN05)
		for _, tag := range pickle.Tags {
			t := strings.TrimPrefix(tag.Name, "@")
			if strings.HasPrefix(t, controlPattern) && !strings.Contains(t, "tlp-") {
				control = t
				break
			}
		}
	}

	f.currentResult = &SummaryResult{
		Control:      control,
		Scenario:     pickle.Name,
		ScenarioName: scenarioName,
		Badge:        exclusionTag,
		IsPolicy:     isPolicy,

		exclusionTag: exclusionTag,
	}
}

func (f *SummaryFormatter) finalizeResult() {
	if f.currentResult == nil {
		return
	}
	r := f.currentResult
	outcome := "PASSING"
	switch r.exclusionTag {
	case "NotTested":
		outcome = "FAILING"
	case "NotTestable", "Duplicate":
		outcome = "PASSING"
	default:
		if r.failed {
			outcome = "FAILING"
		}
	}

	summaryCollector.mu.Lock()
	summaryCollector.results = append(summaryCollector.results, SummaryResult{
		Control:      r.Control,
		Scenario:     r.Scenario,
		ScenarioName: r.ScenarioName,
		IsPolicy:     r.IsPolicy,
		Badge:        r.Badge,
		Outcome:      outcome,
	})
	summaryCollector.mu.Unlock()

	f.currentResult = nil
}

// TestRunStarted is required by the formatters.Formatter interface
func (f *SummaryFormatter) TestRunStarted() {}

// TestRunFinished is required by the formatters.Formatter interface
func (f *SummaryFormatter) TestRunFinished(msg *messages.TestRunFinished) {}

// Summary finalizes the last scenario; the actual report is generated by GenerateSummaryReport
func (f *SummaryFormatter) Summary() {
	if f.currentResult != nil {
		f.finalizeResult()
	}
}

// Defined is required by the formatters.Formatter interface
func (f *SummaryFormatter) Defined(pickle *messages.Pickle, step *messages.PickleStep, def *formatters.StepDefinition) {
}

// Passed is required by the formatters.Formatter interface
func (f *SummaryFormatter) Passed(pickle *messages.Pickle, step *messages.PickleStep, def *formatters.StepDefinition) {
	// No action - we determine outcome when scenario completes
}

// Skipped is required by the formatters.Formatter interface
func (f *SummaryFormatter) Skipped(pickle *messages.Pickle, step *messages.PickleStep, def *formatters.StepDefinition) {
	// Skipped steps usually follow a failure; scenario is already failed
	if f.currentResult != nil {
		f.currentResult.failed = true
	}
}

// Undefined is required by the formatters.Formatter interface
func (f *SummaryFormatter) Undefined(pickle *messages.Pickle, step *messages.PickleStep, def *formatters.StepDefinition) {
	if f.currentResult != nil {
		f.currentResult.failed = true
	}
}

// Failed is required by the formatters.Formatter interface
func (f *SummaryFormatter) Failed(pickle *messages.Pickle, step *messages.PickleStep, def *formatters.StepDefinition, err error) {
	if f.currentResult != nil {
		f.currentResult.failed = true
	}
}

// Pending is required by the formatters.Formatter interface
func (f *SummaryFormatter) Pending(pickle *messages.Pickle, step *messages.PickleStep, def *formatters.StepDefinition) {
	if f.currentResult != nil {
		f.currentResult.failed = true
	}
}

// NewSummaryFormatter creates a summary formatter that collects results for later report generation
func NewSummaryFormatter(suite string, out io.Writer) formatters.Formatter {
	return &SummaryFormatter{out: out}
}

// SummaryData holds the aggregated summary for report generation
type SummaryData struct {
	Control                  string
	PassingPolicy            []string
	PassingPolicyBadges      []string
	FailingPolicy            []string
	FailingPolicyBadges      []string
	PassingBehavioural       []string
	PassingBehaviouralBadges []string
	FailingBehavioural       []string
	FailingBehaviouralBadges []string
}

// GenerateSummaryReport produces summary.html and prints to the console.
// Call this after all test runs have completed.
func GenerateSummaryReport(outputDir string) error {
	summaryCollector.mu.Lock()
	results := make([]SummaryResult, len(summaryCollector.results))
	copy(results, summaryCollector.results)
	summaryCollector.results = nil
	summaryCollector.mu.Unlock()

	// Aggregate by control -> columns -> scenario names
	byControl := make(map[string]*SummaryData)
	for _, r := range results {
		if !strings.HasPrefix(r.Control, controlPattern) {
			continue
		}
		if byControl[r.Control] == nil {
			byControl[r.Control] = &SummaryData{Control: r.Control}
		}
		d := byControl[r.Control]
		scenarioName := r.ScenarioName
		if scenarioName == "" {
			scenarioName = r.Scenario
		}
		switch {
		case r.IsPolicy && r.Outcome == "PASSING":
			d.PassingPolicy = append(d.PassingPolicy, scenarioName)
			d.PassingPolicyBadges = append(d.PassingPolicyBadges, r.Badge)
		case r.IsPolicy && r.Outcome == "FAILING":
			d.FailingPolicy = append(d.FailingPolicy, scenarioName)
			d.FailingPolicyBadges = append(d.FailingPolicyBadges, r.Badge)
		case !r.IsPolicy && r.Outcome == "PASSING":
			d.PassingBehavioural = append(d.PassingBehavioural, scenarioName)
			d.PassingBehaviouralBadges = append(d.PassingBehaviouralBadges, r.Badge)
		case !r.IsPolicy && r.Outcome == "FAILING":
			d.FailingBehavioural = append(d.FailingBehavioural, scenarioName)
			d.FailingBehaviouralBadges = append(d.FailingBehaviouralBadges, r.Badge)
		}
	}

	// Sort controls for deterministic output
	controls := make([]string, 0, len(byControl))
	for c := range byControl {
		controls = append(controls, c)
	}
	sort.Strings(controls)

	html := generateSummaryHTML(controls, byControl)
	summaryPath := filepath.Join(outputDir, "summary.html")
	if err := os.WriteFile(summaryPath, []byte(html), 0644); err != nil {
		return fmt.Errorf("write summary.html: %w", err)
	}

	// Print to console
	text := generateSummaryText(controls, byControl)
	fmt.Println(text)

	return nil
}

func generateSummaryHTML(controls []string, byControl map[string]*SummaryData) string {
	var buf bytes.Buffer
	buf.WriteString(`<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CCC Compliance Test Summary</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .container { max-width: 1400px; margin: 0 auto; background: white; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); overflow-x: auto; }
        h1 { color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
        th { background: #2196F3; color: white; }
        tr:nth-child(even) { background: #f9f9f9; }
        .passing { background: #e8f5e9; }
        .failing { background: #ffebee; }
        .noop { background: #fff8e1; }
        .cell-list { margin: 0; padding-left: 16px; }
        .cell-list li { margin: 4px 0; }
        .badge { display: inline-block; padding: 4px 10px; margin: 2px 0; border-radius: 12px;
            font-size: 0.9em; font-weight: 500; }
        .badge-passing { background: #c8e6c9; color: #2e7d32; border: 1px solid #81c784; }
        .badge-failing { background: #ffcdd2; color: #c62828; border: 1px solid #e57373; }
    </style>
</head>
<body>
    <div class="container">
        <h1>CCC Compliance Test Summary</h1>
        <table>
            <thead>
                <tr>
                    <th>Control</th>
                    <th class="passing">PASSING @Policy</th>
                    <th class="failing">FAILING @Policy</th>
                    <th class="passing">PASSING @Behavioural</th>
                    <th class="failing">FAILING @Behavioural</th>
                </tr>
            </thead>
            <tbody>
`)
	for _, ctrl := range controls {
		d := byControl[ctrl]
		buf.WriteString("                <tr>\n")
		buf.WriteString(fmt.Sprintf("                    <td><strong>%s</strong></td>\n", escapeHTML(ctrl)))
		buf.WriteString(fmt.Sprintf("                    <td class=\"passing\">%s</td>\n", scenarioListHTML(d.PassingPolicy, d.PassingPolicyBadges, "passing")))
		buf.WriteString(fmt.Sprintf("                    <td class=\"failing\">%s</td>\n", scenarioListHTML(d.FailingPolicy, d.FailingPolicyBadges, "failing")))
		buf.WriteString(fmt.Sprintf("                    <td class=\"passing\">%s</td>\n", scenarioListHTML(d.PassingBehavioural, d.PassingBehaviouralBadges, "passing")))
		buf.WriteString(fmt.Sprintf("                    <td class=\"failing\">%s</td>\n", scenarioListHTML(d.FailingBehavioural, d.FailingBehaviouralBadges, "failing")))
		buf.WriteString("                </tr>\n")
	}
	buf.WriteString(`            </tbody>
        </table>
    </div>
</body>
</html>`)
	return buf.String()
}

func scenarioListHTML(scenarios []string, badges []string, badgeType string) string {
	if len(scenarios) == 0 {
		return "—"
	}
	var b strings.Builder
	b.WriteString("<ul class=\"cell-list\">")
	for i, s := range scenarios {
		b.WriteString("<li>")
		b.WriteString(escapeHTML(s))
		if badges[i] != "" {
			b.WriteString("<span class=\"badge badge-" + badgeType + "\">")
			b.WriteString(escapeHTML(badges[i]))
			b.WriteString("</span>")
		}
		b.WriteString("</li>")
	}
	b.WriteString("</ul>")
	return b.String()
}

func escapeHTML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}

func generateSummaryText(controls []string, byControl map[string]*SummaryData) string {
	var buf bytes.Buffer
	headers := []string{"Control", "PASSING @Policy", "FAILING @Policy", "PASSING @Behavioural", "FAILING @Behavioural"}
	controlColWidth := 55 // Wide enough for "CCC.XXX.YYYY.ARZZ - Description"
	colWidth := 20
	separatorLen := controlColWidth + 4*(3+colWidth) // control + 4 columns with " | "

	buf.WriteString("\n" + strings.Repeat("=", separatorLen) + "\n")
	buf.WriteString("CCC Compliance Test Summary\n")
	buf.WriteString(strings.Repeat("=", separatorLen) + "\n\n")
	pad := func(s string, w int) string {
		if len(s) >= w {
			return s[:w-2] + ".."
		}
		return s + strings.Repeat(" ", w-len(s))
	}

	buf.WriteString(pad(headers[0], controlColWidth))
	for _, h := range headers[1:] {
		buf.WriteString(" | ")
		buf.WriteString(pad(h, colWidth))
	}
	buf.WriteString("\n")
	buf.WriteString(strings.Repeat("-", separatorLen))
	buf.WriteString("\n")

	for _, ctrl := range controls {
		d := byControl[ctrl]
		row := []string{
			ctrl,
			strings.Join(d.PassingPolicy, ", "),
			strings.Join(d.FailingPolicy, ", "),
			strings.Join(d.PassingBehavioural, ", "),
			strings.Join(d.FailingBehavioural, ", "),
		}
		buf.WriteString(pad(row[0], controlColWidth))
		for _, cell := range row[1:] {
			buf.WriteString(" | ")
			buf.WriteString(pad(cell, colWidth))
		}
		buf.WriteString("\n")
		// If any cell has multiple scenarios, print them on following lines
		allCells := [][]string{d.PassingPolicy, d.FailingPolicy, d.PassingBehavioural, d.FailingBehavioural}
		maxLen := 0
		for _, c := range allCells {
			if len(c) > maxLen {
				maxLen = len(c)
			}
		}
		for i := 1; i < maxLen; i++ {
			buf.WriteString(strings.Repeat(" ", controlColWidth))
			for _, col := range allCells {
				buf.WriteString(" | ")
				if i < len(col) {
					buf.WriteString(pad(col[i], colWidth))
				} else {
					buf.WriteString(strings.Repeat(" ", colWidth))
				}
			}
			buf.WriteString("\n")
		}
	}

	buf.WriteString(strings.Repeat("=", separatorLen) + "\n")
	return buf.String()
}
