name: Links

on:
  workflow_call:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - title: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base . --verbose --accept 429 --no-progress './**/*.md'
          output: lychee/results.md
          token: ${{ secrets.GITHUB_TOKEN }}
          fail: true
