name: Links

on:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lychee
        uses: taiki-e/install-action@v2
        with:
          tool: lychee@0.24.2

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lychee \
            --root-dir "${GITHUB_WORKSPACE}" \
            --verbose \
            --no-progress \
            --max-retries 5 \
            --retry-wait-time 2 \
            --accept '200..=299,429' \
            './**/*.md'
