## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
jobs:
  lint_pr_title:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: jmeridth/reusable-workflows/.github/workflows/pr-title.yaml@d788c4f6994c7b37134a9f592fe5db42fd7a0957
    with:
      types: |
        ci
        docs
        feat
        fix
      scopes: |
        add
        category
        change
        controls
        family
        remove
        threats
      requireScope: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
