name: "PR Workflow"

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-auto-formatter:
    needs: [run-linting-check, link-checker]
    uses: ./.github/workflows/auto-formatter.yml
    permissions:
      pull-requests: write
      contents: read
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-linting-check:
    uses: ./.github/workflows/linting-check.yml
    permissions:
      pull-requests: write

  link-checker:
    uses: ./.github/workflows/links.yml
    permissions:
      pull-requests: write
      contents: read
