name: "PR Workflow"

on:
  pull_request:
jobs:
  run-linting-check:
    uses: ./.github/workflows/linting_check.yml
    permissions:
      pull-requests: write

  link-checker:
    uses: ./.github/workflows/links.yml
    permissions:
      pull-requests: write
      contents: read

  yaml-checker:
    uses: ./.github/workflows/yaml_check.yml
    permissions:
      pull-requests: write
      contents: read

  todo-checker:
    uses: ./.github/workflows/todo_check.yml
    permissions:
      pull-requests: write
      contents: read

  cloud-api-integration:
    uses: ./.github/workflows/cloud-api-integration.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      id-token: write
