name: "PR Workflow"

on:
  pull_request:
jobs:
  run-format-check:
    uses: ./.github/workflows/format_check.yml
    permissions:
      pull-requests: write
      contents: read

  run-linting-check:
    uses: ./.github/workflows/linting_check.yml
    permissions:
      pull-requests: write

  link-checker:
    uses: ./.github/workflows/links.yml
    permissions:
      pull-requests: write
      contents: read

  yaml-checker:
    uses: ./.github/workflows/yaml_check.yml
    permissions:
      pull-requests: write
      contents: read

  todo-checker:
    uses: ./.github/workflows/todo_check.yml
    permissions:
      pull-requests: write
      contents: read
