name: "PR Workflow"

on:
  pull_request:
  workflow_call:

jobs:
  run-format-check:
    uses: ./.github/workflows/format-check.yml
    permissions:
      pull-requests: write
      contents: read

  run-linting-check:
    uses: ./.github/workflows/linting-check.yml
    permissions:
      pull-requests: write

  link-checker:
    uses: ./.github/workflows/links.yml
    permissions:
      pull-requests: write
      contents: read

  yaml-checker:
    uses: ./.github/workflows/yaml-check.yml
    permissions:
      pull-requests: write
      contents: read

  todo-checker:
    uses: ./.github/workflows/todo-check.yml
    permissions:
      pull-requests: write
      contents: read

  # validation-checker:
  #   uses: ./.github/workflows/validation-check.yml
  #   permissions:
  #     pull-requests: write
  #     contents: read
