name: Auto Close Stale Meeting Issues

on:
  schedule:
    - cron: "18 22 * * *"

jobs:
  close-stale-meeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 13
          days-before-issue-close: 1 # Marked as stale the day before closing
          stale-issue-label: "stale_meeting"
          stale-issue-message: "This issue is stale because it has been open for 13 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          only-labels: "meeting"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
