name: Validation

on:
  workflow_dispatch: # Manual trigger until this is compatible with the revised schema

jobs:
  validate-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FINOS CCC Validator
        uses: sshiells-scottlogic/finos-ccc-validator@1.2.1
        with:
          targetDir: "./services"
