name: Validation

on:
  workflow_call:

jobs:
  validate-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FINOS CCC Validator
        uses: sshiells-scottlogic/finos-ccc-validator@1.2.0
        with:
          targetDir: "./services"
