name: YAML Check

on:
    workflow_call:

jobs:
  yaml-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate YAML Schema
        uses: InoUno/yaml-ls-check@develop
        with:
            schemaMapping: |
              {
                "docs/governance/community-guidelines/templates/schemas/controls-schema.json": [ "services/**/controls.yml", "services/**/controls.yaml" ],
                "docs/governance/community-guidelines/templates/schemas/features-schema.json": [ "services/**/features.yml", "services/**/features.yaml" ],
                "docs/governance/community-guidelines/templates/schemas/metadata-schema.json": [ "services/**/metadata.yml", "services/**/metadata.yaml" ],
                "docs/governance/community-guidelines/templates/schemas/threats-schema.json": [ "services/**/threats.yml", "services/**/threats.yaml" ]
              }
